apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: crypgo-app 
  labels: 
    app: crypgo-app 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: crypgo-app 

  template: 
    metadata: 
      labels: 
        app: crypgo-app
    spec: 
      terminationGracePeriodSeconds: 30 
      containers: 
      - name: crypgo-app 
        image: techadvocate247/crypgo:latest 
        imagePullPolicy: "Always" 
        ports: 
        - containerPort: 3000 

 