apiVersion: v1 
kind: Service 
metadata: 
  name: crypgo-app  
  labels: 
    app: crypgo-app  
spec: 
  type: LoadBalancer 
  ports: 
  - port: 80 
    targetPort: 3000 
  selector: 
    app: crypgo-app  
